#!/usr/bin/env python3
"""
Schema pull: download property definitions and pipeline structures from HubSpot.

Writes:
  10-crm/schemas/{object_type}/properties.json   — all non-archived properties
  10-crm/schemas/{object_type}/pipelines.json    — deal, ticket, order pipelines only
  config/id_manifest.json                        — auto-generated ID map for agents

Run via:
  bash ./scripts/op_run.sh python3 scripts/crm_schema_pull.py
or:
  npm run hubspot:crm:schema

Commit the output. Agents read config/id_manifest.json to resolve human names → IDs.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from hubspot_object_reports import HubSpotClient, get_token  # noqa: E402

BASE_DIR = Path(__file__).parent.parent
SCHEMAS_DIR = BASE_DIR / "10-crm" / "schemas"
CONFIG_DIR = BASE_DIR / "config"

# Standard objects to pull schemas for.
SCHEMA_OBJECTS = [
    "contacts",
    "companies",
    "deals",
    "tickets",
    "leads",
    "products",
    "line_items",
    "quotes",
    "orders",
    "subscriptions",
    "invoices",
]

# Objects that have pipeline/stage structures.
PIPELINE_OBJECTS = ["deals", "tickets", "orders"]


def _pull_properties(client: HubSpotClient, object_type: str) -> list[dict]:
    props = [p for p in client.get_properties(object_type) if not p.get("archived", False)]
    # Sort: HubSpot-native first (alphabetical by group+name), custom last.
    props.sort(key=lambda p: (not p.get("hubspotDefined", False), p.get("groupName", ""), p["name"]))
    return [
        {
            "name": p["name"],
            "label": p.get("label", p["name"]),
            "type": p.get("type", ""),
            "fieldType": p.get("fieldType", ""),
            "groupName": p.get("groupName", ""),
            "hubspotDefined": bool(p.get("hubspotDefined", False)),
            "formField": bool(p.get("formField", False)),
            "description": p.get("description", ""),
            "options": [
                {
                    "label": o.get("label", ""),
                    "value": o.get("value", ""),
                    "displayOrder": o.get("displayOrder", 0),
                }
                for o in (p.get("options") or [])
                if not o.get("hidden", False)
            ],
        }
        for p in props
    ]


def _pull_pipelines(client: HubSpotClient, object_type: str) -> list[dict]:
    try:
        return client.request_json("GET", f"/crm/v3/pipelines/{object_type}").get("results", [])
    except RuntimeError:
        return []


def _write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {path.relative_to(BASE_DIR)}")


def _build_id_manifest(
    portal_id: str,
    custom_objects: list,
    pipelines_by_object: dict[str, list[dict]],
) -> dict:
    pipelines_out: dict = {}
    for obj_type, pipelines in pipelines_by_object.items():
        pipelines_out[obj_type] = [
            {
                "id": p["id"],
                "label": p.get("label", p["id"]),
                "stages": {
                    stage.get("label", stage["id"]): stage["id"]
                    for stage in p.get("stages", [])
                },
            }
            for p in pipelines
        ]

    custom_out: dict = {}
    for descriptor in custom_objects:
        custom_out[descriptor.label] = {
            "objectTypeId": descriptor.object_type,
            "aliases": list(descriptor.aliases),
        }

    return {
        "_note": "Auto-generated by scripts/crm_schema_pull.py — do not edit by hand.",
        "_generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "portal": {
            "HUBSPOT_ACCOUNT__PRIMARY__PORTAL_ID": portal_id,
        },
        "custom_objects": custom_out,
        "pipelines": pipelines_out,
    }


def main() -> int:
    portal_id = os.environ.get("HUBSPOT_ACCOUNT__PRIMARY__PORTAL_ID", "")
    print("CRM schema pull from HubSpot...", flush=True)
    client = HubSpotClient(get_token())

    custom_objects = client.list_custom_objects()
    all_objects = list(SCHEMA_OBJECTS) + [d.object_type for d in custom_objects]
    pipeline_objects = list(PIPELINE_OBJECTS) + [d.object_type for d in custom_objects]

    pipelines_by_object: dict[str, list[dict]] = {}

    for obj_type in all_objects:
        label = obj_type
        print(f"\n[{label}]", flush=True)
        obj_dir = SCHEMAS_DIR / obj_type.replace("/", "_").replace(".", "-")

        # Properties
        print("  pulling properties...", flush=True)
        try:
            props = _pull_properties(client, obj_type)
            _write_json(obj_dir / "properties.json", props)
        except RuntimeError as exc:
            print(f"  ERROR: {exc}", file=sys.stderr)

        # Pipelines
        if obj_type in pipeline_objects:
            print("  pulling pipelines...", flush=True)
            try:
                pipelines = _pull_pipelines(client, obj_type)
                if pipelines:
                    _write_json(obj_dir / "pipelines.json", pipelines)
                    pipelines_by_object[obj_type] = pipelines
            except RuntimeError as exc:
                print(f"  ERROR: {exc}", file=sys.stderr)

    # id_manifest.json
    print("\n[id_manifest.json]", flush=True)
    manifest = _build_id_manifest(portal_id, custom_objects, pipelines_by_object)
    _write_json(CONFIG_DIR / "id_manifest.json", manifest)

    print("\nDone. Commit 10-crm/schemas/ and config/id_manifest.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
